osx_image: xcode10
language: objective-c
cache: cocoapods
podfile: Example/Podfile

before_install:
  - gem install cocoapods
  - pod install --project-directory=Example

before_script:
  - swiftlint

script:
  - set -o pipefail && xcodebuild -workspace Example/MaterialActivityIndicator.xcworkspace -scheme Example -sdk iphonesimulator12.0 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint --swift-version=4.2
